-- I3DION Spatial Database Schema Reference
-- NOTE: The authoritative primary database schema for I3DION Spatial is located at:
-- backend/src/db/schema.sql
--
-- Please refer to backend/src/db/schema.sql for all table definitions, migrations, and relationships.
