import { TemplateDefinition } from '../../types/studio';

export const productShowcaseTemplate: TemplateDefinition = {
  id: 'tmpl_product_showcase',
  name: 'Industrial Technical Showcase',
  description: 'High-impact technical product presentation layout with specs, media, and enterprise demo CTA.',
  category: 'product',
  useCase: 'Industrial Machinery, Enterprise Hardware, Engineering Equipment',
  version: 1,
  access: 'free',
  previewMetadata: {
    tags: ['Industrial', 'Technical Specs', 'Hardware', 'Enterprise'],
    icon: 'Cpu',
    themeColor: '#0f172a',
  },
  canvasConfig: {
    viewport: 'desktop',
    width: 1200,
    height: 960,
    backgroundColor: '#0f172a',
  },
  supportedCapabilities: ['Spec Overview', 'High-Res Media', 'Demo Booking CTA'],
  initialWidgetTree: [
    {
      id: 'showcase_hero_container',
      type: 'container',
      name: 'Hero Header Banner',
      properties: {
        backgroundColor: '#1e293b',
        borderColor: '#334155',
        borderWidth: 1,
        borderRadius: 16,
        padding: 32,
        minHeight: 180,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'flex-start',
        shadow: 'lg',
      },
      children: [],
    },
    {
      id: 'showcase_title_text',
      type: 'text',
      name: 'Product Title',
      properties: {
        content: 'PRO-SERIES X100 SPATIAL SCANNER',
        variant: 'h1',
        fontSize: 32,
        fontWeight: 'bold',
        color: '#f8fafc',
        textAlign: 'left',
        lineHeight: 1.2,
      },
    },
    {
      id: 'showcase_subtitle_text',
      type: 'text',
      name: 'Product Subtitle',
      properties: {
        content: 'Next-Generation Sub-Millimeter Optical Spatial Measurement System',
        variant: 'body1',
        fontSize: 16,
        fontWeight: 'normal',
        color: '#94a3b8',
        textAlign: 'left',
        lineHeight: 1.5,
      },
    },
    {
      id: 'showcase_body_container',
      type: 'container',
      name: 'Product Body Section',
      properties: {
        backgroundColor: '#0f172a',
        borderColor: '#1e293b',
        borderWidth: 1,
        borderRadius: 16,
        padding: 24,
        minHeight: 340,
        flexDirection: 'column',
        justifyContent: 'flex-start',
        alignItems: 'stretch',
        shadow: 'none',
      },
      children: [],
    },
    {
      id: 'showcase_image_media',
      type: 'image',
      name: 'Product Showcase Asset',
      properties: {
        src: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
        alt: 'Pro-Series X100 Spatial Scanner',
        objectFit: 'cover',
        height: 280,
        borderRadius: 12,
      },
    },
    {
      id: 'showcase_specs_text',
      type: 'text',
      name: 'Key Technical Specs',
      properties: {
        content: '• Precision Accuracy: ±0.005mm\n• Scan Rate: 2.4 Million pts/sec\n• Laser Wavelength: 450nm Blue Optics\n• IP67 Rugged Enclosure',
        variant: 'body2',
        fontSize: 14,
        fontWeight: 'normal',
        color: '#cbd5e1',
        textAlign: 'left',
        lineHeight: 1.6,
      },
    },
    {
      id: 'showcase_action_container',
      type: 'container',
      name: 'Conversion Action Bar',
      properties: {
        backgroundColor: '#1e293b',
        borderColor: '#3b82f6',
        borderWidth: 1,
        borderRadius: 12,
        padding: 20,
        minHeight: 100,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        shadow: 'md',
      },
      children: [],
    },
    {
      id: 'showcase_primary_cta',
      type: 'button',
      name: 'Request Demo CTA',
      properties: {
        label: 'Request Technical Demo & Datasheet',
        variant: 'primary',
        backgroundColor: '#2563eb',
        textColor: '#ffffff',
        borderRadius: 8,
        fullWidth: true,
      },
    },
  ],
};
