import { TemplateDefinition } from '../../types/studio';

export const salesConversionTemplate: TemplateDefinition = {
  id: 'tmpl_sales_conversion',
  name: 'Lead Generation & Sales Conversion',
  description: 'Conversion-optimized product presentation designed for instant inquiries, quote requests, and lead capture.',
  category: 'sales',
  useCase: 'Product Launches, Direct Sales Campaigns, Inbound Lead Generation',
  version: 1,
  access: 'free',
  previewMetadata: {
    tags: ['Sales', 'High Conversion', 'Lead Capture', 'Quote CTA'],
    icon: 'TrendingUp',
    themeColor: '#059669',
  },
  canvasConfig: {
    viewport: 'desktop',
    width: 1200,
    height: 980,
    backgroundColor: '#ffffff',
  },
  supportedCapabilities: ['Direct Lead Capture', 'Instant Quote Button', 'Benefit Highlight Grid'],
  initialWidgetTree: [
    {
      id: 'sales_hero_banner',
      type: 'container',
      name: 'Sales Hero Banner',
      properties: {
        backgroundColor: '#f0fdf4',
        borderColor: '#bbf7d0',
        borderWidth: 1,
        borderRadius: 16,
        padding: 32,
        minHeight: 200,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        shadow: 'sm',
      },
      children: [],
    },
    {
      id: 'sales_headline_text',
      type: 'text',
      name: 'Conversion Headline',
      properties: {
        content: 'Transform Your Spatial Workflow in 30 Days',
        variant: 'h1',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#065f46',
        textAlign: 'center',
        lineHeight: 1.2,
      },
    },
    {
      id: 'sales_subheadline_text',
      type: 'text',
      name: 'Value Proposition Subheadline',
      properties: {
        content: 'Accelerate sales conversion by 40% with interactive 3D product visualizations & instant AR quotes.',
        variant: 'body1',
        fontSize: 16,
        fontWeight: 'normal',
        color: '#047857',
        textAlign: 'center',
        lineHeight: 1.5,
      },
    },
    {
      id: 'sales_media_container',
      type: 'container',
      name: 'Product Visual Section',
      properties: {
        backgroundColor: '#ffffff',
        borderColor: '#e5e7eb',
        borderWidth: 1,
        borderRadius: 16,
        padding: 24,
        minHeight: 300,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'stretch',
        shadow: 'md',
      },
      children: [],
    },
    {
      id: 'sales_product_image',
      type: 'image',
      name: 'Featured Product Asset',
      properties: {
        src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
        alt: 'Spatial Platform Sales Dashboard',
        objectFit: 'cover',
        height: 240,
        borderRadius: 10,
      },
    },
    {
      id: 'sales_benefits_text',
      type: 'text',
      name: 'Key Business Benefits',
      properties: {
        content: '✓ Zero technical setup required\n✓ Instant web browser & mobile AR viewing\n✓ Direct integration with I3DION Lead Pipeline',
        variant: 'body1',
        fontSize: 15,
        fontWeight: 'normal',
        color: '#1f2937',
        textAlign: 'left',
        lineHeight: 1.8,
      },
    },
    {
      id: 'sales_lead_cta_container',
      type: 'container',
      name: 'Instant Quote Lead Box',
      properties: {
        backgroundColor: '#064e3b',
        borderColor: '#047857',
        borderWidth: 1,
        borderRadius: 16,
        padding: 28,
        minHeight: 140,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        shadow: 'xl',
      },
      children: [],
    },
    {
      id: 'sales_lead_title_text',
      type: 'text',
      name: 'Lead Box Title',
      properties: {
        content: 'Ready to Elevate Your Sales Experience?',
        variant: 'h3',
        fontSize: 20,
        fontWeight: 'bold',
        color: '#ffffff',
        textAlign: 'center',
        lineHeight: 1.3,
      },
    },
    {
      id: 'sales_primary_quote_btn',
      type: 'button',
      name: 'Get Instant Quote CTA',
      properties: {
        label: 'Get Instant Quote / Contact Sales',
        variant: 'primary',
        backgroundColor: '#10b981',
        textColor: '#ffffff',
        borderRadius: 8,
        fullWidth: true,
      },
    },
  ],
};
